=== Incia94/nagaina/config/config-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"aliasing" : {
			"type" : "array",
			"uniqueItems" : true,
			"items" : {
				"type" : "object",
				"properties": {
					"name" : {
						"type" : "string"
					},
					"deprecation" : {
						"type" : "boolean"
					},
					"target" : {
						"type" : "string"
					}
				},
				"required" : [
					"name", "target"
				]
			}
		},
		"item": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"data": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"content": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"file": {
									"type": [
										"null", "string"
									]
								},
								"seed": {
									"type": "string",
									"pattern" : "[A-Fa-f0-9]+"
								},
								"ring" : {
									"type" : "object",
									"additionalProperties" : false,
									"required" : [
										"cache", "size"
									],
									"properties" : {
										"cache" : {
											"type" : "integer",
											"minimum" : 1
										},
										"size" : {
											"oneOf" : [
												{
													"type": "integer",
													"minimum" : 1
												},
												{
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?"
												}
											]
										}
									}
								}
							},
							"required": [
								"file", "seed", "ring"
							]
						}
					},
					"required": [
						"content"
					]
				},
				"input": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"file": {
							"type": [
								"null", "string"
							]
						},
						"path": {
							"type": [
								"null", "string"
							]
						}
					},
					"required": [
						"file", "path"
					]
				},
				"naming": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"type": {
							"type": "string",
							"enum" : [
								"asc", "desc", "random"
							]
						},
						"prefix": {
							"type": [
								"null", "string"
							]
						},
						"radix": {
							"type": "integer",
							"minimum" : 2,
							"maximum" : 36
						},
						"offset": {
							"type": "integer",
							"minimum" : 0
						},
						"length": {
							"type": "integer",
							"minimum" : 1
						}
					},
					"required": [
						"type", "prefix", "radix", "offset", "length"
					]
				},
				"output": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"delay" : {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 0
								},
								{
									"type" : "string",
									"pattern" : "[\\d]+[SsMmHhDd]?"
								}
							]
						},
						"file": {
							"type": [
								"null", "string"
							]
						},
						"path": {
							"type": [
								"null", "string"
							]
						}
					},
					"required": [
						"delay", "file", "path"
					]
				},
				"type" : {
					"enum" : [
						"data", "path", "token"
					]
				}
			},
			"required": [
				"data", "input", "naming", "output"
			]
		},
		"storage": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"auth": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"file": {
							"type" : [
								"null", "string"
							]
						},
						"secret": {
							"type": [
								"null", "string"
							]
						},
						"token": {
							"type": [
								"null", "string"
							]
						},
						"uid": {
							"type" : [
								"null", "string"
							]
						}
					},
					"required": [
						"file", "secret", "token", "uid"
					]
				},
				"mock": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"capacity": {
							"type": "integer",
							"minimum" : 0
						},
						"container": {
							"type": "object",
							"properties": {
								"capacity": {
									"type": "integer",
									"minimum" : 0
								},
								"countLimit": {
									"type": "integer",
									"minimum" : 0
								}
							},
							"required": [
								"capacity", "countLimit"
							]
						},
						"fail" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"connections" : {
									"type" : "integer",
									"minimum" : 0
								},
								"responses" : {
									"type" : "integer",
									"minimum" : 0
								}
							},
							"required" : [
								"connections", "responses"
							]
						},
						"node" : {
							"type" : "boolean"
						}
					},
					"required": [
						"capacity", "container", "fail", "node"
					]
				},
				"net" : {
					"type" : "object",
					"additionalProperties" : false,
					"properties" : {
						"bindBacklogSize": {
							"type": "integer",
							"minimum" : 0
						},
						"interestOpQueued": {
							"type": "boolean"
						},
						"keepAlive": {
							"type": "boolean"
						},
						"linger": {
							"type": "integer",
							"minimum" : 0
						},
						"rcvBuf" : {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 0
								},
								{
									"type" : "string",
									"pattern" : "[\\d\\.]+[KMGTPE]?B?"
								}
							]
						},
						"reuseAddr": {
							"type": "boolean"
						},
						"sndBuf" : {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 0
								},
								{
									"type" : "string",
									"pattern" : "[\\d\\.]+[KMGTPE]?B?"
								}
							]
						},
						"tcpNoDelay": {
							"type": "boolean"
						},
						"timeoutMilliSec": {
							"type": "integer",
							"minimum" : 0
						},
						"ssl" : {
							"type" : "boolean"
						},
						"http": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"fsAccess": {
									"type": "boolean"
								},
								"headers": {
									"type": "object",
									"properties": {
									}
								},
								"namespace": {
									"type": [
										"null",
										"string"
									]
								},
								"versioning": {
									"type": "boolean"
								}
							},
							"required": [
								"fsAccess", "headers", "namespace", "versioning"
							]
						},
						"node" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"port" : {
									"type" : "number",
									"minimum" : 1
								}
							},
							"required" : [
								"port"
							]
						}
					},
					"required" : [
						"bindBacklogSize", "interestOpQueued", "keepAlive", "linger",
						"rcvBuf", "reuseAddr", "sndBuf", "tcpNoDelay", "timeoutMilliSec", "ssl",
						"http", "node"
					]
				}
			},
			"required": [
				"auth", "mock"
			]
		},
		"test" : {
			"type" : "object",
			"required" : [
				"step"
			],
			"additionalProperties" : false,
			"properties" : {
				"step" : {
					"type" : "object",
					"required" : [
						"limit", "metrics", "name"
					],
					"additionalProperties" : false,
					"properties" : {
						"limit" : {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"count": {
									"type": "integer",
									"minimum" : 0
								},
								"rate": {
									"type": "number",
									"minimum" : 0
								},
								"size": {
									"oneOf" : [
										{
											"type": "integer",
											"minimum" : 0
										},
										{
											"type" : "string",
											"pattern" : "[\\d\\.]+[KMGTPE]?B?\\-?[\\d\\.]?[KMGTPE]?B?"
										}
									]
								},
								"time": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										},
										{
											"type" : "string",
											"pattern" : "[\\d]+[SsMmHhDd]?"
										}
									]
								}
							},
							"required": [
								"count", "rate", "size", "time"
							]
						},
						"metrics" : {
							"type" : "object",
							"required" : [
								"period", "threshold"
							],
							"additionalProperties" : false,
							"properties" : {
								"period" : {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d]+[SsMmHhDd]?"
										}
									]
								},
								"threshold" : {
									"type" : "number",
									"minimum" : 0,
									"maximum" : 1
								}
							}
						},
						"name" : {
							"type" : [
								"null", "string"
							]
						}
					}
				}
			}
		},
		"version" : {
			"type" : "string"
		}
	},
	"required": [
		"item",
		"storage",
		"test",
		"version"
	]
}

=== Incia94/nagaina/config/defaults.json
{
	"item" : {
		"data" : {
			"content" : {
				"file" : null,
				"seed" : "7a42d9c483244167",
				"ring" : {
					"cache" : 25,
					"size" : "4MB"
				}
			}
		},
		"input" : {
			"file" : null,
			"path" : null
		},
		"naming" : {
			"type" : "random",
			"prefix" : null,
			"radix" : 36,
			"offset" : 0,
			"length" : 12
		},
		"output" : {
			"delay" : 0,
			"file" : null,
			"path" : null
		}
	},
	"storage" : {
		"auth" : {
			"file" : null,
			"secret" : null,
			"token" : null,
			"uid" : null
		},
		"mock" : {
			"capacity" : 1000000,
			"container" : {
				"capacity" : 1000000,
				"countLimit" : 1000000
			},
			"fail" : {
				"connections" : 0,
				"responses" : 0
			},
			"node": false
		},
		"net" : {
			"bindBacklogSize" : 0,
			"interestOpQueued" : false,
			"keepAlive" : true,
			"linger" : 0,
			"reuseAddr" : true,
			"rcvBuf" : 0,
			"sndBuf" : 0,
			"tcpNoDelay" : true,
			"timeoutMilliSec" : 0,
			"ssl" : false,
			"http" : {
				"fsAccess" : false,
				"headers" : {
					"Connection" : "Keep-Alive",
					"User-Agent" : "nagaina/3.6.10"
				},
				"namespace" : null,
				"versioning" : false
			},
			"node": {
				"port" : 9020
			}
		}
	},
	"test" : {
		"step" : {
			"limit" : {
				"count" : 0,
				"rate" : 0,
				"size" : 0,
				"time" : "0s"
			},
			"metrics" : {
				"period" : "10s",
				"threshold" : 0
			},
			"name" : null
		}
	},
	"version" : "3.6.10",
	"aliasing" : [
		{
			"name" : "run-id",
			"deprecated" : true,
			"target" : "test-step-name"
		},
		{
			"name" : "atmos-subtenant",
			"target" : "storage-auth-token"
		},
		{
			"name" : "s3-input-bucket",
			"target" : "item-input-path"
		},
		{
			"name" : "s3-output-bucket",
			"target" : "item-output-path"
		},
		{
			"name" : "swift-input-container",
			"target" : "item-input-path"
		},
		{
			"name" : "swift-output-container",
			"target" : "item-output-path"
		},
		{
			"name" : "socket-bindBacklogSize",
			"deprecated" : true,
			"target" : "storage-net-bindBacklogSize"
		},
		{
			"name" : "socket-interestOpQueued",
			"deprecated" : true,
			"target" : "storage-net-interestOpQueued"
		},
		{
			"name" : "socket-keepAlive",
			"deprecated" : true,
			"target" : "storage-net-keepAlive"
		},
		{
			"name" : "socket-linger",
			"deprecated" : true,
			"target" : "storage-net-linger"
		},
		{
			"name" : "socket-reuseAddr",
			"deprecated" : true,
			"target" : "storage-net-reuseAddr"
		},
		{
			"name" : "socket-rcvBuf",
			"deprecated" : true,
			"target" : "storage-net-rcvBuf"
		},
		{
			"name" : "socket-sndBuf",
			"deprecated" : true,
			"target" : "storage-net-sndBuf"
		},
		{
			"name" : "socket-tcpNoDelay",
			"deprecated" : true,
			"target" : "storage-net-tcpNoDelay"
		},
		{
			"name" : "socket-timeoutMilliSec",
			"deprecated" : true,
			"target" : "storage-net-timeOutMilliSec"
		},
		{
			"name" : "storage-ssl",
			"deprecated" : true,
			"target" : "storage-net-ssl"
		},
		{
			"name" : "storage-http-api",
			"deprecated" : true,
			"target" : "storage-driver-type"
		},
		{
			"name" : "socket-http-fsAccess",
			"deprecated" : true,
			"target" : "storage-net-http-fsAccess"
		},
		{
			"name" : "storage-http-headers",
			"deprecated" : true,
			"target" : "storage-net-http-headers"
		},
		{
			"name" : "storage-http-namespace",
			"deprecated" : true,
			"target" : "storage-net-http-namespace"
		},
		{
			"name" : "storage-http-versioning",
			"deprecated" : true,
			"target" : "storage-net-http-versioning"
		},
		{
			"name" : "storage-node-port",
			"deprecated" : true,
			"target" : "storage-net-node-port"
		},
		{
			"name" : "load-job-name",
			"deprecated" : true,
			"target" : "test-step-name"
		},
		{
			"name" : "load-limit-count",
			"deprecated" : true,
			"target" : "test-step-limit-count"
		},
		{
			"name" : "load-limit-rate",
			"deprecated" : true,
			"target" : "test-step-limit-rate"
		},
		{
			"name" : "load-limit-size",
			"deprecated" : true,
			"target" : "test-step-limit-size"
		},
		{
			"name" : "load-limit-time",
			"deprecated" : true,
			"target" : "test-step-limit-time"
		},
		{
			"name" : "load-metrics-period",
			"deprecated" : true,
			"target" : "test-step-metrics-period"
		},
		{
			"name" : "load-metrics-precondition",
			"deprecated" : true,
			"target" : "test-step-precondition"
		},
		{
			"name" : "load-metrics-threshold",
			"deprecated" : true,
			"target" : "test-step-metrics-threshold"
		},
		{
			"name" : "storage-auth-id",
			"deprecated" : true,
			"target" : "storage-auth-uid"
		}
	]
}
